def getSettings_predictsim_no_mtp():
    settings = {
            '0': {'contactConfiguration': '3',
                  'guessType': 'dataDriven',
                  'targetSpeed': 1.33,
                  'N': 50,
                  'tol': 4},
            '1': {'contactConfiguration': '0',
                  'guessType': 'dataDriven',
                  'targetSpeed': 1.33,
                  'N': 50,
                  'tol': 4},
            '2': {'contactConfiguration': '3',
                  'guessType': 'quasiRandom',
                  'targetSpeed': 1.33,
                  'N': 50,
                  'tol': 4},
            '3': {'contactConfiguration': '0',
                  'guessType': 'quasiRandom',
                  'targetSpeed': 1.33,
                  'N': 50,
                  'tol': 4},
            '4': {'contactConfiguration': '3',
                  'guessType': 'dataDriven',
                  'targetSpeed': 1.33,
                  'N': 100,
                  'tol': 4},
            '5': {'contactConfiguration': '0',
                  'guessType': 'dataDriven',
                  'targetSpeed': 1.33,
                  'N': 100,
                  'tol': 4},
            '6': {'contactConfiguration': '3',
                  'guessType': 'quasiRandom',
                  'targetSpeed': 1.33,
                  'N': 100,
                  'tol': 4},
            '7': {'contactConfiguration': '0',
                  'guessType': 'quasiRandom',
                  'targetSpeed': 1.33,
                  'N': 100,
                  'tol': 4}}
    return settings

def getSettings_predictsim_mtp():
    settings = {
            '0': {'guessType': 'dataDriven',
                  'targetSpeed': 1.33,
                  'N': 50,
                  'tol': 4,
                  'adjustAchillesTendonCompliance': False},            
            '1': {'guessType': 'quasiRandom',
                  'targetSpeed': 1.33,
                  'N': 50,
                  'tol': 4,
                  'adjustAchillesTendonCompliance': False},                  
            '2': {'guessType': 'dataDriven',
                  'targetSpeed': 1.33,
                  'N': 100,
                  'tol': 4,
                  'adjustAchillesTendonCompliance': False},            
            '3': {'guessType': 'quasiRandom',
                  'targetSpeed': 1.33,
                  'N': 100,
                  'tol': 4,
                  'adjustAchillesTendonCompliance': False},
            '4': {'guessType': 'dataDriven',
                  'targetSpeed': 1.33,
                  'N': 50,
                  'tol': 4,
                  'adjustAchillesTendonCompliance': True,
                  'AchillesTendonCompliance': 0.8*35},            
            '5': {'guessType': 'quasiRandom',
                  'targetSpeed': 1.33,
                  'N': 50,
                  'tol': 4,
                  'adjustAchillesTendonCompliance': True,
                  'AchillesTendonCompliance': 0.8*35}}
    return settings
