def getSettings():
        
    settings = {
        # %% With toes.        
        # New model.        
        # Effect of the mesh density.
        '0': {'guessType': 'hotStart',
              'targetSpeed': 1.33,
              'N': 50,
              'modelMass': 62},
        '1': {'guessType': 'coldStart',
              'targetSpeed': 1.33,
              'N': 50,
              'modelMass': 62},
        '2': {'guessType': 'hotStart',
              'targetSpeed': 1.33,
              'N': 75,
              'modelMass': 62},
        '3': {'guessType': 'coldStart',
              'targetSpeed': 1.33,
              'N': 75,
              'modelMass': 62},
        '4': {'guessType': 'hotStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62},
        '5': {'guessType': 'coldStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62},
        '6': {'guessType': 'hotStart',
              'targetSpeed': 1.33,
              'N': 125,
              'modelMass': 62},
        '7': {'guessType': 'coldStart',
              'targetSpeed': 1.33,
              'N': 125,
              'modelMass': 62},
        
        # Effect of the convergence tolerance.
        '8': {'guessType': 'hotStart',
              'targetSpeed': 1.33,
              'N': 100,
              'tol': 5,
              'modelMass': 62},
        '9': {'guessType': 'coldStart',
              'targetSpeed': 1.33,
              'N': 100,
              'tol': 5,
              'modelMass': 62},
        '10': {'guessType': 'hotStart',
              'targetSpeed': 1.33,
              'N': 100,
              'tol': 6,
              'modelMass': 62},
        '11': {'guessType': 'coldStart',
              'targetSpeed': 1.33,
              'N': 100,
              'tol': 6,
              'modelMass': 62},
        
        # Effect of the Achilles tensond stiffness.
        '12': {'guessType': 'hotStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62,
              'adjustAchillesTendonStiffness': True,
              'AchillesTendonStiffness': 0.9*35},
        '13': {'guessType': 'coldStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62,
              'adjustAchillesTendonStiffness': True,
              'AchillesTendonStiffness': 0.9*35},
        '14': {'guessType': 'hotStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62,
              'adjustAchillesTendonStiffness': True,
              'AchillesTendonStiffness': 0.8*35},
        '15': {'guessType': 'coldStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62,
              'adjustAchillesTendonStiffness': True,
              'AchillesTendonStiffness': 0.8*35},
        '16': {'guessType': 'hotStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62,
              'adjustAchillesTendonStiffness': True,
              'AchillesTendonStiffness': 0.7*35},
        '17': {'guessType': 'coldStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62,
              'adjustAchillesTendonStiffness': True,
              'AchillesTendonStiffness': 0.7*35},
        '18': {'guessType': 'hotStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62,
              'adjustAchillesTendonStiffness': True,
              'AchillesTendonStiffness': 0.6*35},
        '19': {'guessType': 'coldStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62,
              'adjustAchillesTendonStiffness': True,
              'AchillesTendonStiffness': 0.6*35},
        '20': {'guessType': 'hotStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62,
              'adjustAchillesTendonStiffness': True,
              'AchillesTendonStiffness': 0.5*35},
        '21': {'guessType': 'coldStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62,
              'adjustAchillesTendonStiffness': True,
              'AchillesTendonStiffness': 0.5*35},
        '22': {'guessType': 'hotStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62,
              'adjustAchillesTendonStiffness': True,
              'AchillesTendonStiffness': 0.4*35},
        '23': {'guessType': 'coldStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62,
              'adjustAchillesTendonStiffness': True,
              'AchillesTendonStiffness': 0.4*35},
        '24': {'guessType': 'hotStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62,
              'adjustAchillesTendonStiffness': True,
              'AchillesTendonStiffness': 0.3*35},
        '25': {'guessType': 'coldStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62,
              'adjustAchillesTendonStiffness': True,
              'AchillesTendonStiffness': 0.3*35},
        
        # Old model.
        '26': {'guessType': 'hotStart',
              'targetSpeed': 1.33,
              'N': 100,
              'model': 'old_model',
              'modelMass': 62},
        '27': {'guessType': 'coldStart',
              'targetSpeed': 1.33,
              'N': 100,
              'model': 'old_model',
              'modelMass': 62},
        
        # %% Without toes.
        # New model.
        '28': {'guessType': 'hotStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62,
              'withMTP': False},
        '29': {'guessType': 'coldStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62,
              'withMTP': False},
        
        # Old model.
        '30': {'guessType': 'hotStart',
              'targetSpeed': 1.33,
              'N': 100,
              'model': 'old_model',
              'modelMass': 62,
              'withMTP': False},
        '31': {'guessType': 'coldStart',
              'targetSpeed': 1.33,
              'N': 100,
              'model': 'old_model',
              'modelMass': 62,
              'withMTP': False},
        
        # New model with low contact spheres.
        '32': {'guessType': 'hotStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62,
              'withMTP': False,
              'contactConfiguration': 'generic_low'},
        '33': {'guessType': 'coldStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62,
              'withMTP': False,
              'contactConfiguration': 'generic_low'},
        }    
    
    return settings
