import numpy as np

def getSettings():
        
    settings = {
        # %% Example.        
        # New model.        
        # Effect of the mesh density.
        'example0': {'guessType': 'hotStart',
                    'targetSpeed': 1.33,
                    'N': 50,
                    'modelMass': 62,
                    'model': 'Hamner_modified'},
        'example1': {'guessType': 'hotStart',
                    'targetSpeed': 1.33,
                    'N': 60,
                    'modelMass': 62,
                    'model': 'Hamner_modified'},     
        'example2': {'guessType': 'coldStart',
                    'targetSpeed': 1.33,
                    'N': 60,
                    'modelMass': 62,
                    'model': 'Hamner_modified'},
        'example3': {'guessType': 'hotStart',
                    'targetSpeed': 1.33,
                    'N': 70,
                    'modelMass': 62,
                    'model': 'Hamner_modified'},
        'example4': {'guessType': 'coldStart',
                    'targetSpeed': 1.33,
                    'N': 70,
                    'modelMass': 62,
                    'model': 'Hamner_modified'},                    
        'example5': {'guessType': 'hotStart',
                    'targetSpeed': 1.33,
                    'N': 100,
                    'modelMass': 62,
                    'model': 'Hamner_modified'},
        'example6': {'guessType': 'coldStart',
                    'targetSpeed': 1.33,
                    'N': 100,
                    'modelMass': 62,
                    'model': 'Hamner_modified'},
        'example7': {'guessType': 'coldStart',
                    'targetSpeed': 1.33,
                    'N': 50,
                    'modelMass': 62,
                    'model': 'Hamner_modified'},
        
        # %% With toes.        
        # New model.        
        # Effect of the mesh density.
        '0': {'guessType': 'hotStart',
              'targetSpeed': 1.33,
              'N': 50,
              'modelMass': 62,
              'knee_axis': 'FK'},
        '1': {'guessType': 'coldStart',
              'targetSpeed': 1.33,
              'N': 50,
              'modelMass': 62,
              'knee_axis': 'FK'},
        '2': {'guessType': 'hotStart',
              'targetSpeed': 1.33,
              'N': 75,
              'modelMass': 62,
              'knee_axis': 'FK'},
        '3': {'guessType': 'coldStart',
              'targetSpeed': 1.33,
              'N': 75,
              'modelMass': 62,
              'knee_axis': 'FK'},
        '4': {'guessType': 'hotStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62,
              'knee_axis': 'FK'},
        '5': {'guessType': 'coldStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62,
              'knee_axis': 'FK'},
        '6': {'guessType': 'hotStart',
              'targetSpeed': 1.33,
              'N': 125,
              'modelMass': 62,
              'knee_axis': 'FK'},
        '7': {'guessType': 'coldStart',
              'targetSpeed': 1.33,
              'N': 125,
              'modelMass': 62,
              'knee_axis': 'FK'},
        
        # Effect of the convergence tolerance.
        '8': {'guessType': 'hotStart',
              'targetSpeed': 1.33,
              'N': 100,
              'tol': 5,
              'modelMass': 62,
              'knee_axis': 'FK'},
        '9': {'guessType': 'coldStart',
              'targetSpeed': 1.33,
              'N': 100,
              'tol': 5,
              'modelMass': 62,
              'knee_axis': 'FK'},
        '10': {'guessType': 'hotStart',
              'targetSpeed': 1.33,
              'N': 100,
              'tol': 6,
              'modelMass': 62,
              'knee_axis': 'FK'},
        '11': {'guessType': 'coldStart',
              'targetSpeed': 1.33,
              'N': 100,
              'tol': 6,
              'modelMass': 62,
              'knee_axis': 'FK'},
        
        # Effect of the Achilles tendon stiffness.
        '12': {'guessType': 'hotStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62,
              'knee_axis': 'FK',
              'adjustAchillesTendonStiffness': True,
              'AchillesTendonStiffness': 0.9*35},
        '13': {'guessType': 'coldStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62,
              'knee_axis': 'FK',
              'adjustAchillesTendonStiffness': True,
              'AchillesTendonStiffness': 0.9*35},
        '14': {'guessType': 'hotStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62,
              'knee_axis': 'FK',
              'adjustAchillesTendonStiffness': True,
              'AchillesTendonStiffness': 0.8*35},
        '15': {'guessType': 'coldStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62,
              'knee_axis': 'FK',
              'adjustAchillesTendonStiffness': True,
              'AchillesTendonStiffness': 0.8*35},
        '16': {'guessType': 'hotStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62,
              'knee_axis': 'FK',
              'adjustAchillesTendonStiffness': True,
              'AchillesTendonStiffness': 0.7*35},
        '17': {'guessType': 'coldStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62,
              'knee_axis': 'FK',
              'adjustAchillesTendonStiffness': True,
              'AchillesTendonStiffness': 0.7*35},
        '18': {'guessType': 'hotStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62,
              'knee_axis': 'FK',
              'adjustAchillesTendonStiffness': True,
              'AchillesTendonStiffness': 0.6*35},
        '19': {'guessType': 'coldStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62,
              'knee_axis': 'FK',
              'adjustAchillesTendonStiffness': True,
              'AchillesTendonStiffness': 0.6*35},
        '20': {'guessType': 'hotStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62,
              'knee_axis': 'FK',
              'adjustAchillesTendonStiffness': True,
              'AchillesTendonStiffness': 0.5*35},
        '21': {'guessType': 'coldStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62,
              'knee_axis': 'FK',
              'adjustAchillesTendonStiffness': True,
              'AchillesTendonStiffness': 0.5*35},
        '22': {'guessType': 'hotStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62,
              'knee_axis': 'FK',
              'adjustAchillesTendonStiffness': True,
              'AchillesTendonStiffness': 0.4*35},
        '23': {'guessType': 'coldStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62,
              'knee_axis': 'FK',
              'adjustAchillesTendonStiffness': True,
              'AchillesTendonStiffness': 0.4*35},
        '24': {'guessType': 'hotStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62,
              'knee_axis': 'FK',
              'adjustAchillesTendonStiffness': True,
              'AchillesTendonStiffness': 0.3*35},
        '25': {'guessType': 'coldStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62,
              'knee_axis': 'FK',
              'adjustAchillesTendonStiffness': True,
              'AchillesTendonStiffness': 0.3*35},
        
        # Old model.
        '26': {'guessType': 'hotStart',
              'targetSpeed': 1.33,
              'N': 100,
              'model': 'old_model',
              'modelMass': 62,
              'knee_axis': 'FK'},
        '27': {'guessType': 'coldStart',
              'targetSpeed': 1.33,
              'N': 100,
              'model': 'old_model',
              'modelMass': 62,
              'knee_axis': 'FK'},
        
        # %% Without toes.
        # New model.
        '28': {'guessType': 'hotStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62,
              'knee_axis': 'FK',
              'withMTP': False},
        '29': {'guessType': 'coldStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62,
              'knee_axis': 'FK',
              'withMTP': False},
        
        # Old model.
        '30': {'guessType': 'hotStart',
              'targetSpeed': 1.33,
              'N': 100,
              'model': 'old_model',
              'knee_axis': 'FK',
              'modelMass': 62,
              'withMTP': False},
        '31': {'guessType': 'coldStart',
              'targetSpeed': 1.33,
              'N': 100,
              'model': 'old_model',
              'knee_axis': 'FK',
              'modelMass': 62,
              'withMTP': False},
        
        # New model with low contact spheres.
        '32': {'guessType': 'hotStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62,
              'knee_axis': 'FK',
              'withMTP': False,
              'contactConfiguration': 'generic_low'},
        '33': {'guessType': 'coldStart',
              'targetSpeed': 1.33,
              'N': 100,
              'modelMass': 62,
              'knee_axis': 'FK',
              'withMTP': False,
              'contactConfiguration': 'generic_low'},
        
        # %% Effet of the damping value
        # Critically damped spring for given mass and stiffness. We subtract
        # 0.1 because there is already some damping as part of limit torques.
        '34': {'guessType': 'hotStart',
               'targetSpeed': 1.33,
               'N': 100,
               'modelMass': 62,
               'knee_axis': 'FK',
               'dampingMtp': np.sqrt(4*0.17866389231100815*25) - 0.1},
        '35': {'guessType': 'coldStart',
               'targetSpeed': 1.33,
               'N': 100,
               'modelMass': 62,
               'knee_axis': 'FK',
               'dampingMtp': np.sqrt(4*0.17866389231100815*25) - 0.1},
        '36': {'guessType': 'hotStart',
               'targetSpeed': 1.33,
               'N': 100,
               'modelMass': 62,
               'knee_axis': 'FK',
               'dampingMtp': np.sqrt(4*0.17866389231100815*25)*2-0.1},
        '37': {'guessType': 'coldStart',
               'targetSpeed': 1.33,
               'N': 100,
               'modelMass': 62,
               'knee_axis': 'FK',
               'dampingMtp': np.sqrt(4*0.17866389231100815*25)*2-0.1},
        '38': {'guessType': 'hotStart',
               'targetSpeed': 1.33,
               'N': 100,
               'modelMass': 62,
               'knee_axis': 'FK',
               'dampingMtp': 0.9},
        '39': {'guessType': 'coldStart',
               'targetSpeed': 1.33,
               'N': 100,
               'modelMass': 62,
               'knee_axis': 'FK',
               'dampingMtp': 0.9} ,
        '40': {'guessType': 'hotStart',
               'targetSpeed': 1.33,
               'N': 100,
               'modelMass': 62,
               'knee_axis': 'FK',
               'dampingMtp': 1.9},
        '41': {'guessType': 'coldStart',
               'targetSpeed': 1.33,
               'N': 100,
               'modelMass': 62,
               'knee_axis': 'FK',
               'dampingMtp': 1.9} 
        }    
    
    return settings
